//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrawPokerBasic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DrawPokerBasic.Resources.Resource_US", typeof(Resource_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Poker Basic.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string btnAbout {
            get {
                return ResourceManager.GetString("btnAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet.
        /// </summary>
        internal static string btnBet {
            get {
                return ResourceManager.GetString("btnBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal.
        /// </summary>
        internal static string btnDeal {
            get {
                return ResourceManager.GetString("btnDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw.
        /// </summary>
        internal static string btnDraw {
            get {
                return ResourceManager.GetString("btnDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string btnOptions {
            get {
                return ResourceManager.GetString("btnOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play!.
        /// </summary>
        internal static string btnPlay {
            get {
                return ResourceManager.GetString("btnPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy.
        /// </summary>
        internal static string btnStrategy {
            get {
                return ResourceManager.GetString("btnStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOLD.
        /// </summary>
        internal static string HoldComment {
            get {
                return ResourceManager.GetString("HoldComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        internal static string lblCredits {
            get {
                return ResourceManager.GetString("lblCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Table.
        /// </summary>
        internal static string lblPayTable {
            get {
                return ResourceManager.GetString("lblPayTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound?.
        /// </summary>
        internal static string lblSound {
            get {
                return ResourceManager.GetString("lblSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight Flush.
        /// </summary>
        internal static string LineOne_01 {
            get {
                return ResourceManager.GetString("LineOne_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four of Kind.
        /// </summary>
        internal static string LineOne_02 {
            get {
                return ResourceManager.GetString("LineOne_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 to a Royal Flush.
        /// </summary>
        internal static string LineOne_03 {
            get {
                return ResourceManager.GetString("LineOne_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Pair or better.
        /// </summary>
        internal static string LineOne_04 {
            get {
                return ResourceManager.GetString("LineOne_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4  to a Straight Flush.
        /// </summary>
        internal static string LineOne_05 {
            get {
                return ResourceManager.GetString("LineOne_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Pair.
        /// </summary>
        internal static string LineOne_06 {
            get {
                return ResourceManager.GetString("LineOne_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 to a Royal Flush.
        /// </summary>
        internal static string LineOne_07 {
            get {
                return ResourceManager.GetString("LineOne_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 to a Flush.
        /// </summary>
        internal static string LineOne_08 {
            get {
                return ResourceManager.GetString("LineOne_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-K-Q-J mixed suit.
        /// </summary>
        internal static string LineOne_09 {
            get {
                return ResourceManager.GetString("LineOne_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 suited high cards.
        /// </summary>
        internal static string LineOne_10 {
            get {
                return ResourceManager.GetString("LineOne_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 card Straight Flush.
        /// </summary>
        internal static string LineOne_11 {
            get {
                return ResourceManager.GetString("LineOne_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K-Q-J mixed suit.
        /// </summary>
        internal static string LineOne_12 {
            get {
                return ResourceManager.GetString("LineOne_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 high cards.
        /// </summary>
        internal static string LineOne_13 {
            get {
                return ResourceManager.GetString("LineOne_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 high card.
        /// </summary>
        internal static string LineOne_14 {
            get {
                return ResourceManager.GetString("LineOne_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 suited cards.
        /// </summary>
        internal static string LineOne_15 {
            get {
                return ResourceManager.GetString("LineOne_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Even if you have King high Straight Flush, take the payout!.
        /// </summary>
        internal static string LineTwo_01 {
            get {
                return ResourceManager.GetString("LineTwo_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a no brainer, hold on to them and take the payout!.
        /// </summary>
        internal static string LineTwo_02 {
            get {
                return ResourceManager.GetString("LineTwo_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go for Royal Flush even if you have a natural Flush or Straight..
        /// </summary>
        internal static string LineTwo_03 {
            get {
                return ResourceManager.GetString("LineTwo_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep natural flushes and straights and don&apos;t split a pair..
        /// </summary>
        internal static string LineTwo_04 {
            get {
                return ResourceManager.GetString("LineTwo_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can win with flush, straight, and straight flush..
        /// </summary>
        internal static string LineTwo_05 {
            get {
                return ResourceManager.GetString("LineTwo_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep the high pair to at least win your bet back..
        /// </summary>
        internal static string LineTwo_06 {
            get {
                return ResourceManager.GetString("LineTwo_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This includes the 10 if it matches suit..
        /// </summary>
        internal static string LineTwo_07 {
            get {
                return ResourceManager.GetString("LineTwo_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19% chance to hit the Flush..
        /// </summary>
        internal static string LineTwo_08 {
            get {
                return ResourceManager.GetString("LineTwo_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any card 10 or higher and you win..
        /// </summary>
        internal static string LineTwo_09 {
            get {
                return ResourceManager.GetString("LineTwo_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is better than holding 3 high cards of mixed suit..
        /// </summary>
        internal static string LineTwo_10 {
            get {
                return ResourceManager.GetString("LineTwo_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be consecutive numbers of same suit (example: 6-7-8)..
        /// </summary>
        internal static string LineTwo_11 {
            get {
                return ResourceManager.GetString("LineTwo_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chance of high pair and a outside Straight draw..
        /// </summary>
        internal static string LineTwo_12 {
            get {
                return ResourceManager.GetString("LineTwo_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 high cards are better than holding on to 1 high card..
        /// </summary>
        internal static string LineTwo_13 {
            get {
                return ResourceManager.GetString("LineTwo_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistically better than drawing 5 new cards..
        /// </summary>
        internal static string LineTwo_14 {
            get {
                return ResourceManager.GetString("LineTwo_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have no high cards, this is better than discarding everything..
        /// </summary>
        internal static string LineTwo_15 {
            get {
                return ResourceManager.GetString("LineTwo_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You lose.
        /// </summary>
        internal static string LoseComment {
            get {
                return ResourceManager.GetString("LoseComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Royal Flush.
        /// </summary>
        internal static string payHand1 {
            get {
                return ResourceManager.GetString("payHand1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight Flush.
        /// </summary>
        internal static string payHand2 {
            get {
                return ResourceManager.GetString("payHand2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four of Kind.
        /// </summary>
        internal static string payHand3 {
            get {
                return ResourceManager.GetString("payHand3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full House.
        /// </summary>
        internal static string payHand4 {
            get {
                return ResourceManager.GetString("payHand4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flush.
        /// </summary>
        internal static string payHand5 {
            get {
                return ResourceManager.GetString("payHand5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight.
        /// </summary>
        internal static string payHand6 {
            get {
                return ResourceManager.GetString("payHand6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three of a Kind.
        /// </summary>
        internal static string payHand7 {
            get {
                return ResourceManager.GetString("payHand7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Pair.
        /// </summary>
        internal static string payHand8 {
            get {
                return ResourceManager.GetString("payHand8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jacks or Better.
        /// </summary>
        internal static string payHand9 {
            get {
                return ResourceManager.GetString("payHand9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StrategyImage_01 {
            get {
                return ResourceManager.GetString("StrategyImage_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StrategyImage_02 {
            get {
                return ResourceManager.GetString("StrategyImage_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StrategyImage_03 {
            get {
                return ResourceManager.GetString("StrategyImage_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StrategyImage_04 {
            get {
                return ResourceManager.GetString("StrategyImage_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StrategyImage_05 {
            get {
                return ResourceManager.GetString("StrategyImage_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StrategyImage_06 {
            get {
                return ResourceManager.GetString("StrategyImage_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StrategyImage_07 {
            get {
                return ResourceManager.GetString("StrategyImage_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StrategyImage_08 {
            get {
                return ResourceManager.GetString("StrategyImage_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StrategyImage_09 {
            get {
                return ResourceManager.GetString("StrategyImage_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StrategyImage_10 {
            get {
                return ResourceManager.GetString("StrategyImage_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You win.
        /// </summary>
        internal static string WinComment {
            get {
                return ResourceManager.GetString("WinComment", resourceCulture);
            }
        }
    }
}
